CA2_IMeet/Models/Booking.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CA2_IMeet.Models
{
    public class Booking
    {
        [Key]
        public int BookingId { get; set; }

        [Required(ErrorMessage = "Indicate Meeting Reference.")]
        [StringLength(55, ErrorMessage = "Meeting Title cannot be longer than 55 characters.")]
        [Display(Name = "Meeting Title")]
        public string MeetingReference { get; set; }

        [Required]
        [Display(Name = "Room")]
        public int RoomId { get; set; }
        [ForeignKey("RoomId")]
        public virtual MeetingRoom MeetingRoom { get; set; }

        [Required(ErrorMessage = "Indicate meeting date.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        [Required(ErrorMessage = "Indicate when meeting starts.")]
        [DataType(DataType.Time)]
        [Display(Name = "Start Time")]
        public DateTime Start_DateTime { get; set; }

        [Required(ErrorMessage = "Indicate when meeting ends.")]
        [DataType(DataType.Time)]
        [Display(Name = "End Time")]
        public DateTime End_DateTime { get; set; }

        [Required]
        [Display(Name = "Meeting Owner")]
        public string UserId { get; set; }

        //method to check if room is not already booked on another booking
        public bool IsValidBooking(Booking newBooking)
        {
            if (newBooking.RoomId == RoomId && newBooking.Date == Date)
            {
                if((newBooking.Start_DateTime > End_DateTime) || (newBooking.End_DateTime < Start_DateTime))
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            else
            {
                return true;
            }
        }
    }
}

CA2_IMeet/Models/BookingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CA2_IMeet.Models
{
    public class BookingViewModel
    {
        private DateTime start_DateTime;
        private DateTime end_DateTime;

        [HiddenInput]
        public int? BookingId { get; set; }

        [Required(ErrorMessage = "Indicate Meeting Reference.")]
        [StringLength(55, ErrorMessage = "Meeting Title cannot be longer than 55 characters.")]
        [Display(Name = "Meeting Title")]
        public string MeetingReference { get; set; }

        [Required(ErrorMessage = "Indicate meeting date.")]
        [DataType(DataType.Date)]
        [Weekdays]
        [InFuture]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        [Required(ErrorMessage = "Indicate when meeting starts.")]
        [DataType(DataType.Time)]
        [Display(Name = "Start Time")]
        public DateTime Start_DateTime
        {
            get
            {
                return start_DateTime;
            }
            set
            {
                start_DateTime = new DateTime(Date.Year, Date.Month, Date.Day, value.Hour, 0, 1);
            }
        }

        [Required(ErrorMessage = "Indicate when meeting ends.")]
        [DataType(DataType.Time)]
        [Display(Name = "End Time")]
        public DateTime End_DateTime
        {
            get
            {
                return end_DateTime;
            }
            set
            {
                end_DateTime = new DateTime(Date.Year, Date.Month, Date.Day, value.Hour, 0, 0);
            }
        }

        public bool InvalidStartAndEnd()
        {
            if (Start_DateTime >= End_DateTime)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
    }
}

CA2_IMeet/Controllers/MeetingRoomsController.cs
using CA2_IMeet.DAL;
using CA2_IMeet.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace CA2_IMeet.Controllers
{
    [Authorize]
    public class MeetingRoomsController : Controller
    {

        //private BookingContext db = new BookingContext();
        private IBookingContext db = new BookingContext();

        public MeetingRoomsController() { }

        public MeetingRoomsController(IBookingContext context)
        {
            db = context;
        }

        // GET: MeetingRooms
        public ActionResult Index(string sortOrder, string searchString)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.SizeSortParm = sortOrder == "Size" ? "size_desc" : "Size";
            var rooms = from r in db.MeetingRooms
                        select r;

            if (!String.IsNullOrEmpty(searchString))
            {
                rooms = rooms.Where(r => r.Name.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    rooms = rooms.OrderByDescending(r => r.Name);
                    break;
                case "Size":
                    rooms = rooms.OrderBy(r => r.Size);
                    break;
                case "size_desc":
                    rooms = rooms.OrderByDescending(r => r.Size);
                    break;
                default:
                    rooms = rooms.OrderBy(r => r.Name);
                    break;
            }
            return View(rooms.ToList());
        }

        // GET: MeetingRooms/Details/{keyword}
        public ActionResult Details(string keyword)
        {
            if (String.IsNullOrEmpty(keyword))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MeetingRoom meetingRoom = db.MeetingRooms.Where(n => n.Name == keyword).FirstOrDefault();
            if (meetingRoom == null)
            {
                return HttpNotFound();
            }
            return View(meetingRoom);
        }

        // GET: MeetingRooms/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: MeetingRooms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Size,Location,Equipment")] MeetingRoom meetingRoom)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (db.MeetingRooms.FirstOrDefault(m => m.Name == meetingRoom.Name) == null)
                    {
                        db.MeetingRooms.Add(meetingRoom);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "A meeting room with the same name already exists.");
                    }
                }
            }
            catch (RetryLimitExceededException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(meetingRoom);
        }

        // GET: MeetingRooms/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MeetingRoom meetingRoom = db.MeetingRooms.Find(id);
            if (meetingRoom == null)
            {
                return HttpNotFound();
            }
            return View(meetingRoom);
        }

        // POST: MeetingRooms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var roomToUpdate = db.MeetingRooms.Find(id);
            string oldName = roomToUpdate.Name;
            List<string> checkSet = db.MeetingRooms.Select(m => m.Name).ToList();

            if (TryUpdateModel(roomToUpdate, "", new string[] { "Name", "Size", "Location", "Equipment" }))
            {
                try
                {
                    //check that a room with same name does not already exists if name is being changed
                    string newName = roomToUpdate.Name;
                    if (newName != oldName && checkSet.Contains(newName))
                    {
                        ModelState.AddModelError("", "A meeting room with the same name already exists.");                    
                    }
                    else
                    {
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }                  
                }
                catch (RetryLimitExceededException)
                {
                    ModelState.AddModelError("", "Unable to save changes. Please try again, and if the problem persists, contact your system administrator.");
                }
            }
            return View(roomToUpdate);
        }

        // GET: MeetingRooms/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id, bool? saveChangesError=false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Delete failed. Please try again, and if the problem persists, contact your system administrator.";
            }
            MeetingRoom meetingRoom = db.MeetingRooms.Find(id);
            if (meetingRoom == null)
            {
                return HttpNotFound();
            }
            return View(meetingRoom);
        }

        // POST: MeetingRooms/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                MeetingRoom meetingRoomToDelete = db.MeetingRooms.Find(id);
                //check if any meeting is happening in the room at a future date
                Booking bookingUsingRoomInFuture = db.Bookings.FirstOrDefault(x => (x.RoomId == id) && (x.Date >= DateTime.Today));
                if (bookingUsingRoomInFuture == null)
                {
                    db.MeetingRooms.Remove(meetingRoomToDelete);
                    db.SaveChanges();
                }
                else
                {
                    TempData["msg"] = "<script>alert('This meeting room cannot be deleted as it has been booked for future meetings.');</script>";
                }

            }
            catch (RetryLimitExceededException)
            {
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CA2_IMeet/Views/Booking/Create.cshtml
@model CA2_IMeet.Models.BookingCreateViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Find Rooms for a New Booking</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Start_DateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Start_DateTime", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Start_DateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.End_DateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("End_DateTime", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.End_DateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Find Room" formaction=@Url.Action("CreateStep2") class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CA2_IMeet/Views/Booking/CreateStep2.cshtml
@model CA2_IMeet.Models.Booking

@{
    ViewBag.Title = "Create";
}

<h2>Complete Booking</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MeetingReference, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MeetingReference, new { htmlAttributes = new { @class = "form-control", @autofocus = "autofocus" } })
                @Html.ValidationMessageFor(model => model.MeetingReference, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Start_DateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Start_DateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Start_DateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.End_DateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.End_DateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.End_DateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group hidden">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.UserId, new { id = "username", Value = ViewBag.Username })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomId, "RoomId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoomId", null, htmlAttributes: new { @class = "form-control" })
                <small id="roomHelpBlock" class="form-text text-muted">
                    See below for meeting room information.
                </small>
                @Html.ValidationMessageFor(model => model.RoomId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create Meeting" class="btn btn-primary" formaction=@Url.Action("CreatePost", Model) />
                &emsp;
                <a class="btn btn-default" href="@Url.Action("Create", new { Date = Model.Date, End_DateTime = Model.End_DateTime, Start_DateTime = Model.Start_DateTime })">Change Date/Times</a>
            </div>
        </div>
    </div>
}

<hr />

<div>
    <h3>Available Meeting Rooms</h3>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(r => r.MeetingRoom.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(r => r.MeetingRoom.Size)
                </th>
                <th>
                    @Html.DisplayNameFor(r => r.MeetingRoom.Location)
                </th>
                <th>
                    @Html.DisplayNameFor(r => r.MeetingRoom.Equipment)
                </th>
                <th></th>
            </tr>

            @foreach (CA2_IMeet.Models.MeetingRoom item in ViewBag.AvailableRooms)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Size)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Location)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Equipment)
                    </td>
                </tr>
            }
        </table>
    </div>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

CA2_IMeet/Views/Booking/Delete.cshtml
@model CA2_IMeet.Models.Booking

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this Booking?</h3>
<div>
    <h5 class="text-warning">Once you click delete, this action cannot be undone.</h5>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MeetingRoom.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MeetingRoom.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeetingReference)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MeetingReference)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Start_DateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Start_DateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.End_DateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.End_DateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CA2_IMeet/Views/Booking/Details.cshtml
@model CA2_IMeet.Models.Booking

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Booking</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MeetingRoom.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MeetingRoom.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeetingReference)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MeetingReference)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Start_DateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Start_DateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.End_DateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.End_DateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BookingId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CA2_IMeet/Views/Booking/Edit.cshtml
@model CA2_IMeet.Models.BookingEditViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit a Booking</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BookingId)

        <div class="form-group">
            @Html.LabelFor(model => model.MeetingReference, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MeetingReference, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MeetingReference, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Start_DateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Start_DateTime", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Start_DateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.End_DateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("End_DateTime", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.End_DateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomId, "RoomId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoomId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoomId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CA2_IMeet/Views/Booking/Index.cshtml
@using CA2_IMeet.Models
@model IEnumerable<Booking>


@{
    ViewBag.Title = "Index";
    var trClass = HttpContext.Current.User.IsInRole("Admin") ? "" : "hidden";
}

<h2>Your Future Bookings</h2>

<p>
    @Html.ActionLink("Create New Booking", "Create")
</p>

@if (Model.Count() > 0)
{
<table class="table table-striped">
    <tr>    
        <th>
            @Html.DisplayNameFor(model => model.MeetingReference)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            Timeslot
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MeetingRoom.Name)
        </th>
        <th class="@trClass">
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th></th>
    </tr>

@foreach (Booking item in Model) {
    <tr>      
        <td>
            @Html.DisplayFor(modelItem => item.MeetingReference)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @item.Start_DateTime.ToShortTimeString()&ensp;–&ensp;@item.End_DateTime.ToShortTimeString()
        </td>
        <td>
            @Html.ActionLink(@item.MeetingRoom.Name, "Details", "MeetingRooms", new { keyword = item.MeetingRoom.Name }, null)
        </td>
        <td class="@trClass">
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.BookingId }) |
            @Html.ActionLink("Cancel", "Delete", new { id=item.BookingId })
        </td>
    </tr>
}
</table>
}
else
{
    <h3>You do not have any booking for future meetings.</h3>
}